apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx2
spec:
  containers:
  - image: nginx
    name: nginx 
    resources: {}
    ports:
    - containerPort: 90
  dnsPolicy: ClusterFirst    
  restartPolicy: Always
status: {}